### ISSUE TITLE
Update getState to return an array, which could be extracted like react useState.

### ISSUE THREAD

**Issue by rabisnaqvi** [rabisnaqvi/Astral.js#14]
Update getState to return an array, which could be extracted like react useState.
so it would be something like this:
`const [count, onCountChange] = Astral.context.getState('count');`

**Comment by Siar416** [comment]
Hey rabisnaqvi, I changed the getState function to how you mentioned above. How can I create a pull request?

**Comment by Siar416** [comment]
Are you able to give me write access? Or should I fork the repo, make the changes then submit a PR that way?

**Comment by rabisnaqvi** [comment]
Hey @Siar416 , thanks for contributing to this! you can create a branch from the issue, and then generate a PR to merge into the "release-candidate" branch. you can try that, if you face any permission issues then let me know I'll get that sorted.

**Comment by Siar416** [comment]
Thanks for the fast response. I forked the repo and created a branch. Made the changes and submitted a PR from my forked branch to the release-candidate branch. Sent from my iPhoneOn May 24, 2023, at 2:19 PM, Rabis Naqvi ***@***.***> wrote:﻿
Hey @Siar416 , thanks for contributing to this! you can create a branch from the issue, and then generate a PR to merge into the "release-candidate" branch. you can try that, if you face any permission issues then let me know I'll get that sorted.
